INSERT INTO category_tab(cat_name,createdOn) VALUES ('category1',CURDATE());
INSERT INTO category_tab(cat_name,createdOn) VALUES ('category2',CURDATE());
INSERT INTO category_tab(cat_name,createdOn) VALUES ('category3',CURDATE());
INSERT INTO category_tab(cat_name,createdOn) VALUES ('category4',CURDATE());
INSERT INTO category_tab(cat_name,createdOn) VALUES ('category5',CURDATE());
INSERT INTO admin_tab(admin_name,admin_password) VALUES ('admin','admin');
INSERT INTO product_tab( product_category, product_price, product_name, addedOn) VALUES (1,123.45,'product1',CURDATE());
INSERT INTO product_tab( product_category, product_price, product_name, addedOn) VALUES (2,234.89,'product2',CURDATE());
INSERT INTO product_tab( product_category, product_price, product_name, addedOn) VALUES (1,7890.456,'product3',CURDATE());
INSERT INTO product_tab( product_category, product_price, product_name, addedOn) VALUES (4,123.45,'product4',CURDATE());
INSERT INTO product_tab( product_category, product_price, product_name, addedOn) VALUES (5,400.34,'product5',CURDATE());
INSERT INTO product_tab( product_category, product_price, product_name, addedOn) VALUES (3,19999.99,'product6',CURDATE());
INSERT INTO user_tab( firstName,lastName,emailId,password,address,age,createOn) VALUES ('john','doe','john@ex.com','john','123 st,west bank',25,CURDATE());